version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    networks:
      eth0:
        ipv4_address: 192.168.31.11
networks:
  eth0:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.31.0/24
